FROM ubuntu:22.04

RUN apt update
RUN apt -y upgrade
RUN apt install -y python3.11 && ln -s /usr/bin/python3.11 /usr/bin/python3
RUN python3 --version
RUN apt update
RUN apt install -y python3-pip postgresql-contrib

WORKDIR /datapoint
COPY main.py .
COPY src/ ./src
COPY requirements.txt .
COPY .env .
RUN pip3 install -r requirements.txt

ENTRYPOINT ["/bin/bash"]

CMD ["-c", "python3 src/client/station.py --url http://localhost:9000 generate -r A"]
