services:

  haproxy:
    container_name: haproxy
    build:
      context: .
      dockerfile: Dockerfile.haproxy
    depends_on:
      - api0
      - api1
      - api2
      - api3
      - api4
      - api5
    ports:
      - "9000:9000"


  api0:
    container_name: api0
    build:
      context: .
      dockerfile: Dockerfile.api

  api1:
    build:
      context: .
      dockerfile: Dockerfile.api

  api2:
    build:
      context: .
      dockerfile: Dockerfile.api

  api3:
    build:
      context: .
      dockerfile: Dockerfile.api

  api4:
    build:
      context: .
      dockerfile: Dockerfile.api

  api5:
    build:
      context: .
      dockerfile: Dockerfile.api


  station0:
    container_name: station0
    build:
      context: .
      dockerfile: Dockerfile.station
    depends_on:
      - haproxy
    command: --url http://haproxy:9000 generate -r A M

  station1:
    container_name: station1
    build:
      context: .
      dockerfile: Dockerfile.station
    depends_on:
      - haproxy
    command: --url http://haproxy:9000 generate -r B N

  station2:
    container_name: station2
    build:
      context: .
      dockerfile: Dockerfile.station
    depends_on:
      - haproxy
    command: --url http://haproxy:9000 generate -r C O

  station3:
    container_name: station3
    build:
      context: .
      dockerfile: Dockerfile.station
    depends_on:
      - haproxy
    command: --url http://haproxy:9000 generate -r D P

  station4:
    container_name: station4
    build:
      context: .
      dockerfile: Dockerfile.station
    depends_on:
      - haproxy
    command: --url http://haproxy:9000 generate -r E Q

  station5:
    container_name: station5
    build:
      context: .
      dockerfile: Dockerfile.station
    depends_on:
      - haproxy
    command: --url http://haproxy:9000 generate -r F R

  station6:
    container_name: station6
    build:
      context: .
      dockerfile: Dockerfile.station
    depends_on:
      - haproxy
    command: --url http://haproxy:9000 generate -r G S T

  station7:
    container_name: station7
    build:
      context: .
      dockerfile: Dockerfile.station
    depends_on:
      - haproxy
    command: --url http://haproxy:9000 generate -r H U

  station8:
    container_name: station8
    build:
      context: .
      dockerfile: Dockerfile.station
    depends_on:
      - haproxy
    command: --url http://haproxy:9000 generate -r I V

  station9:
    container_name: station9
    build:
      context: .
      dockerfile: Dockerfile.station
    depends_on:
      - haproxy
    command: --url http://haproxy:9000 generate -r J W

  station10:
    container_name: station10
    build:
      context: .
      dockerfile: Dockerfile.station
    depends_on:
      - haproxy
    command: --url http://haproxy:9000 generate -r K X

  station511:
    container_name: station11
    build:
      context: .
      dockerfile: Dockerfile.station
    depends_on:
      - haproxy
    command: --url http://haproxy:9000 generate -r L Y Z

